### Check Server
GET http://localhost:5000/healthcheck
### Register
POST http://localhost:5000/api/users
Content-Type: application/json
{
  "email": "hosh@gmail.com",
  "username": "hosh",
  "password": "password"
}

### Verification
POST http://localhost:5000/api/users/verify/:id/:verificationCode

### Forgot Password
POST http://localhost:5000/api/users/forgotpassword

### 
GET  http://localhost:5000/api/users/me

### Login
POST http://localhost:5000/api/sessions
Content-Type: application/json
{

}

###
POST http://localhost:5000/api/sessions/refresh
